apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: blackbox-roles
  namespace: <set>
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: blackbox-rolebinding
  namespace: ops-monit
subjects:
  - kind: ServiceAccount
    name: blackbox
    namespace: <set>
roleRef:
  kind: Role
  name: blackbox-roles
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-blackbox-exporter
  namespace: <set>
  labels:
    app: prometheus-blackbox-exporter
spec:
  selector:
    matchLabels:
      app: prometheus-blackbox-exporter
  template:
    metadata:
      labels:
        app: prometheus-blackbox-exporter
    spec:
      serviceAccountName: blackbox
      hostAliases:
        - hostnames:
          - k8s-master
          ip: 10.40.210.100
      restartPolicy: Always
      containers:
        - name: blackbox-exporter
          image: "prom/blackbox-exporter:v0.15.1"
          imagePullPolicy: IfNotPresent
          securityContext: