apiVersion: v1
kind: ConfigMap
metadata:
  namespace: <set>
  name: prometheus-blackbox-exporter-<set>
  labels:
    app: prometheus-blackbox-exporter-<set>
data:
  blackbox.yaml: |
    modules:
      tcp_connect:
        prober: tcp
        timeout: 5s
      http_2xx:
        prober: http
        timeout: 5s
        http:
          method: GET
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2
          valid_status_codes:
          - 200
          - 401
          - 403
          tls_config:
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

---

